# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_proto.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emy_proto.proto\x12\x08my_proto\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"!\n\x0f\x43ommandResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2T\n\x0bRaspberryPi\x12\x45\n\x0e\x45xecuteCommand\x12\x18.my_proto.CommandRequest\x1a\x19.my_proto.CommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_proto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMANDREQUEST']._serialized_start=28
  _globals['_COMMANDREQUEST']._serialized_end=61
  _globals['_COMMANDRESPONSE']._serialized_start=63
  _globals['_COMMANDRESPONSE']._serialized_end=96
  _globals['_RASPBERRYPI']._serialized_start=98
  _globals['_RASPBERRYPI']._serialized_end=182
# @@protoc_insertion_point(module_scope)
